### ISSUE TITLE
readme.md: add GNU Arm Embedded Toolchain version

### ISSUE THREAD

**Issue by idea--list** [0xcart/artemis#33]
Have been looking exactly for something like this repo as AmbiqSuiteSDK HAL Api names are so hard to remember... 
Really like the idea how those got wrapped into easy to remember function names. ❤️ 

Followed the readme precisely and installed the latest versions of the dependencies on my Win10x64 computer.
My findings that are not mentioned in readm.md:

- Turns out that the x32 version of Segger J-Link is preferred
- Segger J-Link looks for GNU Arm Embedded Toolchain 9 2020-q2-update and debugging simply aborts if one does not has this particular version installed

So this sentence in the readme is definately outdated:
_The latest version of each tool/extension should be used unless otherwise noted._

**Comment by 0xcart** [comment]
The 64-bit version of Segger J-Link works correctly on Windows 10x64. With regard to version compatibility, I cannot support the numerous combinations of software, especially as they are routinely upgraded at different cadences. Therefore, it's incumbent upon the user of this framework to read associated documentation (e.g., Segger J-Link documentation) to determine which versions of software are compatible with each other. I believe the comment in the instructions, "The latest version of each tool/extension should be used unless otherwise noted", is the correct approach given that updates to software are routinely associated with cybersecurity issues.
