### ISSUE TITLE
Some functions prevent code execution

### ISSUE THREAD

**Issue by idea--list** [0xcart/artemis#34]
Tried to convert /src/artemis_main.c into a blinky, like this:

```
#include "artemis_debug.h"
#include "artemis_mcu.h"
#include "artemis_scheduler.h"
#include "artemis_time.h"
#include "artemis_led.h"
#include <stdlib.h>

///
///
///
int main(void)
{
    // initialize mcu features
    artemis_mcu_initialize();

    // initialize debug features
    artemis_debug_initialize();

    // initialize time functions
    artemis_time_initialize();

    // initialize the scheduler
    artemis_scheduler_initialize();

    // run the application
    artemis_scheduler_run();

    // initialize led
    artemis_led_initialize();

    // Blink forever
    while (1)
    {
        artemis_led_toggle(1);
        artemis_time_delayms(2000);
    }

    return(EXIT_SUCCESS);
}
```

The code compiles but the LED does not blink until i comment out artemis_scheduler_initialize(), artemis_scheduler_run() and also line 33 inside artemis_mcu.c.

Maybe i miss something as i am just beginning with AmbiqSuiteSDK today, but my first impression is this might be a bug.

**Comment by 0xcart** [comment]
If you review the implementation of artemis_scheduler_run() found in artemis_scheduler.c you will see that it enters a while(1) loop. Thus, when you call artemis_scheduler_run() it never exits this function. That is correct behavior. The intent of the scheduler framework is to allow a user to "schedule" different tasks to execute at different rates. Your while(1) loop which appears after artemis_schedule_run() never executes. This is why commenting out artemis_scheduler_run() did the trick. I would recommend reviewing artemis_task.h/c and artemis_scheduler.h/c and understand how they work. You will see there is already an LED "task" that is being executed at 2Hz (see artemis_task.c). Additionally, you will find that artemis_led_initialize() was already being called (via the task/scheduler initialization code).  Your addition of artemis_led_initialize() is actually calling it a second time, and again, never actually gets executed because artemis_scheduler_run() doesn't return.
